name: Source Job

on:
  repository_dispatch:
    types: [trigger-job]

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: tim-corley/simpleWeather
          ref: master

      - name: Step 1
        run: echo "Step 1"

      - name: Copy Directory
        run: |
          mkdir -p destination-dir
          cp -R src/ foobarService/destination-dir
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          
      - name: Commit
        run: |
          git add .
          git commit -m "fresh changes"
          git push origin main
